app:
  name: smart_home
  env: debug
server:
  host: localhost
  port: '8080'
database:
  driver: mysql
  user: root
  password: 123456
  host: 127.0.0.1
  port: '3306'
  db_name: iot_smart_home
  charset: utf8
  show_sql: false
redis:
  addr: 127.0.0.1
  port: '6379'
  password: password
  db: 0